server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/aurora_hotel}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Spring Vector Store Init Configuration
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:db/init-vector-store.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  #  Multipart file config
  spring:
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

  # Spring AI OpenAI Configuration
  ai:
    openai:
      api-key: ${OPEN_ROUTER_API}
      embedding:
        base-url: http://127.0.0.1:1234
        options:
          model: text-embedding-nomic-embed-text-v1.5-embedding
          dimensions: 768
      chat:
        base-url: https://openrouter.ai/api
        api-key: ${OPEN_ROUTER_API}
        options:
          model: mistralai/mistral-small-3.2-24b-instruct:free
          internal-tool-execution-enabled: true
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        max-document-batch-size: 10000
        schema-validation: true
        table-name: vector_store
        initialize-schema: true

# JWT Configuration
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION:3600}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:86400}
